name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * 3' # Runs weekly, on Wednesday as Midnight
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://daniel.scheufler.io/rss2.xml"
  update-readme-with-podcast:
    name: Update this repo's README with latest podcasts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://anchor.fm/s/af2c24c8/podcast/rss"
          comment_tag_name: "PODCAST-LIST"
